import { CheckCircle2, HeartPulse, MapPin, Music2, Phone, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";

export type MusicianApplication = { id: string; user_id: string | null; first_name: string; last_name: string; email: string | null; phone: string | null; whatsapp: string | null; address: string | null; eps: string | null; cali_commune: number | null; emergency_contact_name: string | null; emergency_contact_phone: string | null; status: string; musician_instruments: Array<{ is_primary: boolean; instrument: { name: string } | null }>; musician_roles: Array<{ is_primary: boolean; musical_role: { name: string } | null }>; };
export function MusicianApplicationDialog({ open, onOpenChange, application, pending, onApprove }: { open: boolean; onOpenChange: (open: boolean) => void; application: MusicianApplication | null; pending: boolean; onApprove: () => void }) {
  if (!application) return null;
  const instruments = application.musician_instruments.map((item) => item.instrument?.name).filter(Boolean).join(", ") || "No registrado";
  const roles = application.musician_roles.map((item) => item.musical_role?.name).filter(Boolean).join(", ") || "No registrado";
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-[2rem] sm:max-w-2xl"><DialogHeader><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><UserRound className="size-5" /></span><div><DialogTitle className="text-xl font-black">Solicitud de {application.first_name} {application.last_name}</DialogTitle><DialogDescription>Verifica la información antes de habilitar el portal.</DialogDescription></div></div></DialogHeader><div className="mt-3 grid gap-4 sm:grid-cols-2"><Info icon={Phone} title="Contacto"><Row label="Correo" value={application.email} /><Row label="Teléfono" value={application.phone} /><Row label="WhatsApp" value={application.whatsapp} /></Info><Info icon={MapPin} title="Residencia"><Row label="Dirección" value={application.address} /><Row label="Comuna" value={application.cali_commune ? `Comuna ${application.cali_commune}` : "No indicada"} /></Info><Info icon={HeartPulse} title="Salud y emergencia"><Row label="EPS" value={application.eps} /><Row label="Contacto" value={application.emergency_contact_name} /><Row label="Teléfono" value={application.emergency_contact_phone} /></Info><Info icon={Music2} title="Información musical"><Row label="Instrumento" value={instruments} /><Row label="Rol" value={roles} /><div className="mt-3"><Badge className="rounded-lg bg-primary/10 text-primary">{application.status}</Badge></div></Info></div>{pending && <div className="mt-5 flex justify-end border-t pt-5"><Button onClick={onApprove} className="rounded-xl bg-emerald-600 font-bold hover:bg-emerald-700"><CheckCircle2 className="mr-2 size-4" /> Aprobar músico y activar acceso</Button></div>}</DialogContent></Dialog>;
}
function Info({ icon: Icon, title, children }: { icon: typeof Phone; title: string; children: React.ReactNode }) { return <section className="rounded-2xl border bg-muted/20 p-4"><div className="mb-3 flex items-center gap-2 font-black"><Icon className="size-4 text-primary" />{title}</div><div className="space-y-2">{children}</div></section>; }
function Row({ label, value }: { label: string; value: string | null | undefined }) { return <div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="text-sm font-semibold">{value || "No registrado"}</p></div>; }
