import { supabase } from "@/integrations/supabase/client";
import type { FinanceContext, TransactionStatus, TransactionType } from "./types";

export async function loadFinanceContext(organizationId:string){const{data,error}=await supabase.rpc("get_finance_context",{target_organization_id:organizationId});if(error)throw error;return data as unknown as FinanceContext;}
export async function saveAccount(organizationId:string,userId:string,values:{name:string;account_type:string;opening_balance:number}){const{error}=await supabase.from("financial_accounts").insert({organization_id:organizationId,created_by:userId,...values});if(error)throw error;}
export async function saveTransaction(organizationId:string,userId:string,values:{account_id:string|null;event_id:string|null;client_id:string|null;musician_id:string|null;transaction_type:TransactionType;concept:string;category:string;amount:number;status:TransactionStatus;transaction_date:string;due_date:string|null;payment_method:string|null;notes:string|null}){const now=new Date().toISOString();const{error}=await supabase.from("financial_transactions").insert({organization_id:organizationId,created_by:userId,...values,paid_at:values.status==="PAGADO"?now:null});if(error)throw error;}
export async function updateTransactionStatus(id:string,status:TransactionStatus){const{error}=await supabase.from("financial_transactions").update({status,paid_at:status==="PAGADO"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;}
export async function saveBudgetItem(organizationId:string,userId:string,eventId:string,values:{item_type:"INGRESO"|"EGRESO";category:string;description:string;estimated_amount:number}){const{error}=await supabase.from("event_budget_items").insert({organization_id:organizationId,event_id:eventId,created_by:userId,...values});if(error)throw error;}
export async function deleteBudgetItem(id:string){const{error}=await supabase.from("event_budget_items").delete().eq("id",id);if(error)throw error;}
