import { useCallback, useEffect, useMemo, useState } from "react";
import { addDays, addMonths, addWeeks, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, parseISO, startOfMonth, startOfWeek, subDays, subMonths, subWeeks } from "date-fns";
import { es } from "date-fns/locale";
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, List, MapPin, Plus } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAuth } from "@/contexts/AuthContext";
import { listRehearsals } from "@/features/rehearsals/service";
import type { Rehearsal } from "@/features/rehearsals/types";

export default function CalendarPage() {
  const { membership, hasPermission } = useAuth();
  const navigate = useNavigate();
  const [items, setItems] = useState<Rehearsal[]>([]);
  const [view, setView] = useState("month");
  const [cursor, setCursor] = useState(new Date());
  const load = useCallback(async () => { if (!membership) return; try { setItems(await listRehearsals(membership.organizationId)); } catch { toast.error("No fue posible cargar el calendario"); } }, [membership]);
  useEffect(() => { void load(); }, [load]);
  const move = (direction: number) => setCursor((date) => view === "month" ? (direction > 0 ? addMonths(date, 1) : subMonths(date, 1)) : view === "week" ? (direction > 0 ? addWeeks(date, 1) : subWeeks(date, 1)) : (direction > 0 ? addDays(date, 1) : subDays(date, 1)));
  const monthDays = useMemo(() => eachDayOfInterval({ start: startOfWeek(startOfMonth(cursor), { weekStartsOn: 1 }), end: endOfWeek(endOfMonth(cursor), { weekStartsOn: 1 }) }), [cursor]);
  const weekDays = useMemo(() => eachDayOfInterval({ start: startOfWeek(cursor, { weekStartsOn: 1 }), end: endOfWeek(cursor, { weekStartsOn: 1 }) }), [cursor]);
  const onDate = (date: Date) => items.filter((item) => isSameDay(parseISO(item.rehearsal_date), date));
  const title = view === "month" ? format(cursor, "MMMM yyyy", { locale: es }) : view === "week" ? `${format(weekDays[0], "d MMM", { locale: es })} — ${format(weekDays[6], "d MMM yyyy", { locale: es })}` : format(cursor, "EEEE, d 'de' MMMM", { locale: es });

  return <div className="space-y-6 animate-in fade-in duration-300"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Agenda central</p><h1 className="mt-2 text-3xl font-black tracking-tight">Calendario</h1><p className="mt-2 text-sm text-muted-foreground">Vista coordinada de ensayos; las siguientes fases sumarán eventos, pagos y tareas.</p></div>{hasPermission("rehearsals.manage") && <Button onClick={() => navigate("/ensayos")} className="rounded-xl font-bold"><Plus className="mr-2 size-4" /> Programar ensayo</Button>}</div><Card className="overflow-hidden rounded-[2rem] shadow-none"><div className="flex flex-col gap-4 border-b p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="flex items-center gap-2"><Button variant="outline" size="icon" className="rounded-xl" onClick={() => move(-1)}><ChevronLeft className="size-4" /></Button><Button variant="outline" className="rounded-xl" onClick={() => setCursor(new Date())}>Hoy</Button><Button variant="outline" size="icon" className="rounded-xl" onClick={() => move(1)}><ChevronRight className="size-4" /></Button><h2 className="ml-2 capitalize font-black sm:text-lg">{title}</h2></div><Tabs value={view} onValueChange={setView}><TabsList className="h-auto rounded-xl p-1"><TabsTrigger value="month" className="rounded-lg">Mes</TabsTrigger><TabsTrigger value="week" className="rounded-lg">Semana</TabsTrigger><TabsTrigger value="day" className="rounded-lg">Día</TabsTrigger><TabsTrigger value="list" className="rounded-lg"><List className="mr-1 size-3" /> Lista</TabsTrigger></TabsList></Tabs></div><CardContent className="p-0"><Tabs value={view} onValueChange={setView}><TabsContent value="month" className="m-0"><MonthGrid days={monthDays} cursor={cursor} itemsFor={onDate} onOpen={(id) => navigate(`/ensayos/${id}`)} /></TabsContent><TabsContent value="week" className="m-0"><WeekGrid days={weekDays} itemsFor={onDate} onOpen={(id) => navigate(`/ensayos/${id}`)} /></TabsContent><TabsContent value="day" className="m-0 p-5 sm:p-6"><AgendaList items={onDate(cursor)} empty="No hay actividades programadas para este día." onOpen={(id) => navigate(`/ensayos/${id}`)} /></TabsContent><TabsContent value="list" className="m-0 p-5 sm:p-6"><AgendaList items={items} empty="No hay actividades registradas." onOpen={(id) => navigate(`/ensayos/${id}`)} /></TabsContent></Tabs></CardContent></Card></div>;
}

function MonthGrid({ days, cursor, itemsFor, onOpen }: { days: Date[]; cursor: Date; itemsFor: (date: Date) => Rehearsal[]; onOpen: (id: string) => void }) { return <div className="overflow-x-auto"><div className="min-w-[760px]"><div className="grid grid-cols-7 border-b bg-muted/30">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map((day) => <div key={day} className="p-3 text-center text-[11px] font-bold uppercase tracking-wider text-muted-foreground">{day}</div>)}</div><div className="grid grid-cols-7">{days.map((date) => <div key={date.toISOString()} className={`min-h-32 border-b border-r p-2 ${!isSameMonth(date, cursor) ? "bg-muted/25 text-muted-foreground" : ""}`}><div className={`mb-2 grid size-7 place-items-center rounded-lg text-xs font-bold ${isSameDay(date, new Date()) ? "bg-primary text-primary-foreground" : ""}`}>{format(date, "d")}</div><div className="space-y-1">{itemsFor(date).map((item) => <button key={item.id} onClick={() => onOpen(item.id)} className="w-full rounded-lg bg-primary/10 px-2 py-1.5 text-left text-[10px] font-bold text-primary hover:bg-primary/15"><span className="block truncate">{item.name}</span><span className="opacity-70">{item.start_time.slice(0,5)}</span></button>)}</div></div>)}</div></div></div>; }
function WeekGrid({ days, itemsFor, onOpen }: { days: Date[]; itemsFor: (date: Date) => Rehearsal[]; onOpen: (id: string) => void }) { return <div className="overflow-x-auto"><div className="grid min-w-[760px] grid-cols-7">{days.map((date) => <div key={date.toISOString()} className="min-h-[430px] border-r p-3"><div className="text-center"><p className="text-[10px] font-bold uppercase text-muted-foreground">{format(date, "EEE", { locale: es })}</p><p className={`mx-auto mt-1 grid size-9 place-items-center rounded-xl font-black ${isSameDay(date, new Date()) ? "bg-primary text-primary-foreground" : ""}`}>{format(date, "d")}</p></div><div className="mt-4 space-y-2">{itemsFor(date).map((item) => <button key={item.id} onClick={() => onOpen(item.id)} className="w-full rounded-xl border border-primary/15 bg-primary/5 p-2 text-left"><p className="text-xs font-bold">{item.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.start_time.slice(0,5)} · {item.location}</p></button>)}</div></div>)}</div></div>; }
function AgendaList({ items, empty, onOpen }: { items: Rehearsal[]; empty: string; onOpen: (id: string) => void }) { if (!items.length) return <div className="py-16 text-center"><CalendarDays className="mx-auto size-9 text-primary" /><p className="mt-4 font-bold">{empty}</p></div>; return <div className="space-y-3">{items.map((item) => <button key={item.id} onClick={() => onOpen(item.id)} className="flex w-full flex-col gap-3 rounded-2xl border p-4 text-left transition-colors hover:border-primary/30 hover:bg-primary/5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><Badge className="rounded-lg">ENSAYO</Badge><p className="font-black">{item.name}</p></div><div className="mt-2 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1"><CalendarDays className="size-3" /> {format(parseISO(item.rehearsal_date), "d MMM yyyy", { locale: es })}</span><span className="flex items-center gap-1"><Clock3 className="size-3" /> {item.start_time.slice(0,5)}</span><span className="flex items-center gap-1"><MapPin className="size-3" /> {item.location}</span></div></div><Badge variant="outline" className="w-fit rounded-lg">{item.status}</Badge></button>)}</div>; }
