import { useCallback,useEffect,useMemo,useState } from "react";
import { Building2,Mail,Phone,Search,UserRound,UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Card,CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/contexts/AuthContext";
import { listClients } from "@/features/commercial/service";
import type { Client } from "@/features/commercial/types";
export default function Clients(){const{membership}=useAuth();const[clients,setClients]=useState<Client[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState("");const load=useCallback(async()=>{if(!membership)return;setLoading(true);try{setClients(await listClients(membership.organizationId));}catch(error){toast.error("No fue posible cargar clientes",{description:error instanceof Error?error.message:undefined});}finally{setLoading(false);}},[membership]);useEffect(()=>{void load();},[load]);const filtered=useMemo(()=>clients.filter(c=>`${c.full_name} ${c.company??""} ${c.email} ${c.phone}`.toLowerCase().includes(query.toLowerCase())),[clients,query]);return <div className="space-y-6 animate-in fade-in duration-300"><div><p className="text-xs font-black uppercase tracking-[.16em] text-primary">CRM comercial</p><h1 className="mt-2 text-3xl font-black">Clientes</h1><p className="mt-2 text-sm text-muted-foreground">Contactos creados automáticamente desde solicitudes y conectados con cotizaciones y eventos.</p></div><div className="grid gap-4 sm:grid-cols-3"><Metric icon={UsersRound} label="Clientes" value={clients.length}/><Metric icon={Building2} label="Empresas" value={clients.filter(c=>Boolean(c.company)).length}/><Metric icon={UserRound} label="Con solicitudes" value={clients.filter(c=>(c.quote_requests?.length??0)>0).length}/></div><Card className="rounded-[2rem] shadow-none"><div className="border-b p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente, empresa o contacto…" className="rounded-xl pl-9"/></div></div><CardContent className="p-0">{loading?<div className="space-y-3 p-5">{[1,2,3].map(i=><Skeleton key={i} className="h-20 rounded-2xl"/>)}</div>:<div className="divide-y">{filtered.map(client=><div key={client.id} className="grid gap-4 p-4 sm:grid-cols-[1fr_1fr_150px] sm:items-center sm:px-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><UserRound className="size-5"/></span><div><p className="font-black">{client.full_name}</p><p className="text-xs text-muted-foreground">{client.company||client.client_type}</p></div></div><div className="space-y-1 text-sm"><p className="flex items-center gap-2"><Mail className="size-3 text-primary"/>{client.email}</p><p className="flex items-center gap-2"><Phone className="size-3 text-primary"/>{client.phone}</p></div><div className="flex gap-2"><Badge variant="outline" className="rounded-lg">{client.quote_requests?.length??0} solicitudes</Badge><Badge className="rounded-lg bg-emerald-500/10 text-emerald-700">{client.quotes?.length??0} cotizaciones</Badge></div></div>)}</div>}</CardContent></Card></div>}
function Metric({icon:Icon,label,value}:{icon:typeof UsersRound;label:string;value:number}){return <Card className="rounded-3xl shadow-none"><CardContent className="flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><Icon className="size-5"/></span><div><p className="text-2xl font-black">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>}
