import { useCallback, useEffect, useState } from "react";
import { Database, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { CatalogManager } from "@/features/musicians/CatalogManager";
import { getMusicianCatalogs } from "@/features/musicians/service";
import type { Instrument, MusicalRole } from "@/features/musicians/types";
import { useAuth } from "@/contexts/AuthContext";

export default function RegistrationCatalogs(){const{membership,hasPermission}=useAuth();const[instruments,setInstruments]=useState<Instrument[]>([]);const[roles,setRoles]=useState<MusicalRole[]>([]);const load=useCallback(async()=>{if(!membership)return;try{const data=await getMusicianCatalogs(membership.organizationId);setInstruments(data.instruments);setRoles(data.roles);}catch(error){toast.error("No fue posible cargar los catálogos",{description:error instanceof Error?error.message:undefined});}},[membership]);useEffect(()=>{void load();},[load]);return <div className="space-y-6 animate-in fade-in duration-300"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Base de datos</p><h1 className="mt-2 text-3xl font-black">Listas del registro</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Administra los instrumentos y roles musicales que aparecen en el formulario público de músicos.</p></div><div className="flex gap-3 rounded-2xl border border-primary/15 bg-primary/5 p-4"><Database className="size-5 shrink-0 text-primary"/><div><p className="text-sm font-bold">Catálogo conectado en tiempo real</p><p className="mt-1 text-xs text-muted-foreground">Los registros activos aparecen en la lista desplegable pública; al desactivarlos dejan de ofrecerse sin borrar el historial.</p></div><ShieldCheck className="ml-auto hidden size-5 text-emerald-600 sm:block"/></div>{membership&&<CatalogManager organizationId={membership.organizationId} instruments={instruments} roles={roles} canManage={hasPermission("musicians.manage")} onChanged={()=>void load()}/>}</div>}
