export type QuoteRequestStatus = "NUEVA"|"EN REVISIÓN"|"DISPONIBILIDAD CONFIRMADA"|"DISPONIBILIDAD NO DISPONIBLE"|"COTIZANDO"|"COTIZACIÓN ENVIADA"|"NEGOCIACIÓN"|"ACEPTADA"|"RECHAZADA"|"CANCELADA";
export type AvailabilityResult = "DISPONIBLE"|"REQUIERE REVISIÓN"|"EXISTE CONFLICTO";
export type QuoteStatus = "BORRADOR"|"ENVIADA"|"EN NEGOCIACIÓN"|"ACEPTADA"|"RECHAZADA"|"VENCIDA"|"CANCELADA";
export interface Client { id:string; organization_id:string; client_type:string; full_name:string; company:string|null; nit:string|null; phone:string; whatsapp:string|null; email:string; city:string; created_at:string; quote_requests?: Array<{id:string;status:QuoteRequestStatus}>; quotes?: Array<{id:string;status:QuoteStatus}>; }
export interface QuoteItem { id?:string; description:string; quantity:number; unit:string; unit_price:number; discount:number; total?:number; }
export interface QuoteVersion { id:string; version_number:number; event_snapshot:Record<string,unknown>; commercial_terms:Record<string,string>; subtotal:number; discount:number; total:number; deposit_percent:number; deposit_amount:number; balance_amount:number; observations:string|null; created_at:string; quote_items:QuoteItem[]; }
export interface Quote { id:string; organization_id:string; client_id:string; quote_request_id:string; quote_number:string; status:QuoteStatus; current_version:number; public_token:string; valid_until:string|null; sent_at:string|null; opened_at:string|null; quote_versions:QuoteVersion[]; quote_change_requests?:Array<{id:string;message:string;client_name:string;client_email:string;status:string;created_at:string}>; quote_acceptances?:Array<{id:string;client_name:string;client_email:string;confirmation:string;accepted_at:string;ip_address:string|null;quote_version:{version_number:number}|null}>; }
export interface QuoteRequest { id:string; organization_id:string; client_id:string; request_number:string; event_name:string; event_type:string; event_city:string; venue:string; event_address:string; attendee_count:number; event_date:string; start_time:string; end_time:string; time_preference:string|null; service_type:string; custom_service:string|null; duration_minutes:number; space_type:"INTERIOR"|"EXTERIOR"; has_stage:boolean; has_sound:boolean; has_lighting:boolean; requires_transport:boolean; requires_production:boolean; special_requirements:string|null; budget_range:string|null; status:QuoteRequestStatus; availability_status:AvailabilityResult; availability_notes:string|null; created_at:string; client:Client; quotes:Quote[]; event_availability:Array<{id:string;status:AvailabilityResult;notes:string|null;snapshot:Record<string,unknown>;checked_at:string}>; commercial_timeline:Array<{id:string;action:string;description:string;actor_type:string;metadata:Record<string,unknown>;created_at:string}>; }
export interface PublicQuote { organization:{name:string;logo_url:string|null;phone:string|null;whatsapp:string|null;email:string|null}; quote:{number:string;status:QuoteStatus;version:number;valid_until:string|null;token:string}; client:{name:string;company:string|null;email:string;phone:string}; event:Record<string,string|number|null>; items:QuoteItem[]; summary:{subtotal:number;discount:number;total:number;deposit_percent:number;deposit_amount:number;balance_amount:number}; terms:Record<string,string>; observations:string|null; }
export interface CommercialEvent { id:string; organization_id:string; client_id:string; quote_request_id:string|null; quote_id:string|null; name:string; event_type:string; event_date:string; start_time:string; end_time:string; city:string; venue:string; address:string; attendee_count:number|null; services:Array<Record<string,unknown>>; requirements:string|null; conditions:Record<string,string>; contracted_value:number; status:"PENDIENTE"|"CONFIRMADO"|"EN CURSO"|"REALIZADO"|"CANCELADO"|"CERRADO"; confirmed_at:string|null; setlist_id:string|null; client:Client; event_musicians:Array<{id:string;musician_id:string;status:string;agreed_fee:number;musician:{id:string;first_name:string;last_name:string;specialty:string|null}}>; financial_transactions:Array<{id:string;concept:string;amount:number;status:string;due_date:string|null;paid_at:string|null}>; event_riders:Array<{id:string;status:string;current_version:number;technical_snapshot:Record<string,unknown>}>; }
export interface QuoteRequestForm { full_name:string;company:string;nit:string;phone:string;whatsapp:string;email:string;client_city:string;client_type:string;event_name:string;event_type:string;event_city:string;venue:string;event_address:string;attendee_count:string;event_date:string;start_time:string;end_time:string;time_preference:string;service_type:string;custom_service:string;duration_minutes:string;custom_duration_minutes:string;space_type:"INTERIOR"|"EXTERIOR";has_stage:boolean;has_sound:boolean;has_lighting:boolean;requires_transport:boolean;requires_production:boolean;special_requirements:string;budget_range:string;consent:boolean; }
