// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://lhrsqtxylxtroajneezc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_YYiMh83YIXkArkNagHQR2g_EVQQZx6e";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
