import { useEffect, useState } from "react";
import { FileDown, LoaderCircle, Plus, Save, Send, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { createInitialRider, saveRiderVersion } from "./service";
import type { InputChannel, MonitorMix, ProductionContact, RiderContent, RiderStatus, StagePosition, TechnicalEvent } from "./types";

export function RiderEditorDialog({ event, open, onOpenChange, onSaved }: { event: TechnicalEvent | null; open: boolean; onOpenChange: (open: boolean) => void; onSaved: () => void }) {
  const [content, setContent] = useState<RiderContent | null>(null);
  const [notes, setNotes] = useState("");
  const [saving, setSaving] = useState(false);

  useEffect(() => { if (open && event) { setContent(createInitialRider(event)); setNotes(""); } }, [open, event]);
  if (!event || !content) return null;

  const save = async (status: RiderStatus) => {
    setSaving(true);
    try { await saveRiderVersion(event.id, content, status, notes); toast.success(status === "BORRADOR" ? "Borrador guardado" : status === "LISTO" ? "Rider marcado como listo" : "Rider marcado como enviado"); onSaved(); }
    catch (error) { toast.error("No fue posible guardar el rider", { description: error instanceof Error ? error.message : undefined }); }
    finally { setSaving(false); }
  };

  const field = (section: "sound" | "power" | "logistics", key: string, value: string) => setContent((current) => current ? ({ ...current, [section]: { ...current[section], [key]: value } }) : current);
  const versions = event.rider?.versions ?? [];

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="rider-print-root max-h-[94vh] overflow-y-auto rounded-[2rem] p-0 sm:max-w-6xl"><div className="border-b px-5 py-5 sm:px-7"><DialogHeader><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><Badge className="rounded-lg">{event.rider?.status ?? "NUEVO"}</Badge><Badge variant="outline" className="rounded-lg">Versión {event.rider?.current_version ?? 0}</Badge></div><DialogTitle className="mt-3 text-2xl font-black">Rider · {event.name}</DialogTitle><DialogDescription>{formatDate(event.event_date)} · {event.start_time.slice(0,5)} · {event.venue}, {event.city}</DialogDescription></div><Button type="button" variant="outline" onClick={() => window.print()} className="print:hidden rounded-xl"><FileDown className="mr-2 size-4" />Imprimir / PDF</Button></div></DialogHeader></div>
    <RiderPrintView event={event} content={content} />
    <Tabs defaultValue="general" className="p-5 print:hidden sm:p-7"><TabsList className="print:hidden mb-6 flex h-auto w-full justify-start overflow-x-auto rounded-2xl p-1.5"><TabsTrigger value="general" className="rounded-xl">General</TabsTrigger><TabsTrigger value="stage" className="rounded-xl">Stage plot</TabsTrigger><TabsTrigger value="inputs" className="rounded-xl">Input / patch</TabsTrigger><TabsTrigger value="monitors" className="rounded-xl">Monitores</TabsTrigger><TabsTrigger value="logistics" className="rounded-xl">Logística</TabsTrigger><TabsTrigger value="history" className="rounded-xl">Versiones</TabsTrigger></TabsList>
      <TabsContent value="general" className="space-y-6"><Section title="Información técnica"><div className="grid gap-4 sm:grid-cols-2"><Field label="Contacto técnico" value={content.general.technical_contact} onChange={(value) => setContent({ ...content, general: { ...content.general, technical_contact: value } })} /><Field label="Teléfono técnico" value={content.general.technical_phone} onChange={(value) => setContent({ ...content, general: { ...content.general, technical_phone: value } })} /><Area label="Resumen y requerimientos" value={content.general.summary} onChange={(value) => setContent({ ...content, general: { ...content.general, summary: value } })} className="sm:col-span-2" /></div></Section><div className="grid gap-5 lg:grid-cols-2"><Section title="Sonido"><div className="grid gap-4 sm:grid-cols-2"><Field label="Sistema PA" value={content.sound.pa} onChange={(value) => field("sound","pa",value)} /><Field label="Consola" value={content.sound.console} onChange={(value) => field("sound","console",value)} /><Area label="Micrófonos" value={content.sound.microphones} onChange={(value) => field("sound","microphones",value)} /><Area label="Cajas directas" value={content.sound.di_boxes} onChange={(value) => field("sound","di_boxes",value)} /><Area label="Backline" value={content.sound.backline} onChange={(value) => field("sound","backline",value)} className="sm:col-span-2" /></div></Section><Section title="Iluminación y energía"><Area label="Requerimientos de iluminación" value={content.lighting.requirements} onChange={(value) => setContent({ ...content, lighting: { requirements: value } })} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Voltaje" value={content.power.voltage} onChange={(value) => field("power","voltage",value)} /><Field label="Circuitos" value={content.power.circuits} onChange={(value) => field("power","circuits",value)} /><Field label="Puesta a tierra" value={content.power.grounding} onChange={(value) => field("power","grounding",value)} /><Field label="Notas eléctricas" value={content.power.notes} onChange={(value) => field("power","notes",value)} /></div></Section></div><Section title="Notas finales"><Area label="Observaciones para el productor o venue" value={content.final_notes} onChange={(value) => setContent({ ...content, final_notes: value })} /></Section></TabsContent>
      <TabsContent value="stage"><StageEditor rows={content.stage_plot} onChange={(stage_plot) => setContent({ ...content, stage_plot })} /></TabsContent>
      <TabsContent value="inputs"><InputEditor rows={content.input_list} onChange={(input_list) => setContent({ ...content, input_list })} /></TabsContent>
      <TabsContent value="monitors"><MonitorEditor rows={content.monitor_mixes} onChange={(monitor_mixes) => setContent({ ...content, monitor_mixes })} /></TabsContent>
      <TabsContent value="logistics" className="space-y-6"><Section title="Horarios y acceso"><div className="grid gap-4 sm:grid-cols-2"><Field label="Hora de llegada" type="time" value={content.logistics.arrival_time} onChange={(value) => field("logistics","arrival_time",value)} /><Field label="Prueba de sonido" type="time" value={content.logistics.soundcheck_time} onChange={(value) => field("logistics","soundcheck_time",value)} /><Area label="Carga y descarga" value={content.logistics.load_in} onChange={(value) => field("logistics","load_in",value)} /><Area label="Acceso al lugar" value={content.logistics.access} onChange={(value) => field("logistics","access",value)} /><Area label="Parqueadero" value={content.logistics.parking} onChange={(value) => field("logistics","parking",value)} /><Area label="Transporte" value={content.logistics.transport} onChange={(value) => field("logistics","transport",value)} /><Area label="Hospitality / camerino / alimentación" value={content.logistics.hospitality} onChange={(value) => field("logistics","hospitality",value)} className="sm:col-span-2" /></div></Section><ContactEditor rows={content.contacts} onChange={(contacts) => setContent({ ...content, contacts })} /></TabsContent>
      <TabsContent value="history"><Section title="Historial de versiones"><div className="space-y-3">{versions.map((version) => <div key={version.id} className="flex flex-col gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 font-black text-primary">v{version.version_number}</span><div className="min-w-0 flex-1"><p className="font-black">{version.status}</p><p className="text-xs text-muted-foreground">{new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(version.created_at))}{version.notes ? ` · ${version.notes}` : ""}</p></div><Button type="button" variant="outline" size="sm" onClick={() => setContent(version.content_snapshot)} className="rounded-xl">Usar como base</Button></div>)}{!versions.length && <p className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">La primera versión aparecerá después de guardar.</p>}</div></Section></TabsContent>
      <div className="print:hidden mt-6 grid gap-4 border-t pt-5 lg:grid-cols-[1fr_auto]"><div><Label>Notas de esta versión</Label><Input value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Ej. Ajuste de canales y horarios" className="mt-2 rounded-xl" /></div><div className="flex flex-col gap-2 sm:flex-row lg:items-end"><Button type="button" variant="outline" disabled={saving} onClick={() => void save("BORRADOR")} className="rounded-xl"><Save className="mr-2 size-4" />Guardar borrador</Button><Button type="button" disabled={saving} onClick={() => void save("LISTO")} className="rounded-xl"><Save className="mr-2 size-4" />Marcar listo</Button><Button type="button" disabled={saving} onClick={() => void save("ENVIADO")} className="rounded-xl bg-emerald-600 hover:bg-emerald-700">{saving ? <LoaderCircle className="mr-2 size-4 animate-spin" /> : <Send className="mr-2 size-4" />}Marcar enviado</Button></div></div>
    </Tabs>
  </DialogContent></Dialog>;
}

function RiderPrintView({event,content}:{event:TechnicalEvent;content:RiderContent}){return <div className="hidden space-y-6 p-8 print:block"><div><h1 className="text-3xl font-black">Rider técnico · {event.name}</h1><p>{formatDate(event.event_date)} · {event.start_time.slice(0,5)} · {event.venue}, {event.city}</p><p className="mt-2">Contacto: {content.general.technical_contact} {content.general.technical_phone}</p></div><PrintSection title="Resumen"><p>{content.general.summary||"Sin observaciones"}</p></PrintSection><PrintSection title="Stage plot"><PrintTable headers={["Músico","Posición","Instrumentos","Energía"]} rows={content.stage_plot.map(row=>[row.performer,row.position,row.instruments,row.power])}/></PrintSection><PrintSection title="Input list / patch"><PrintTable headers={["Canal","Fuente","Mic / DI","Soporte","48V"]} rows={content.input_list.map(row=>[row.channel,row.source,row.microphone,row.stand,row.phantom?"Sí":"No"])}/></PrintSection><PrintSection title="Monitores"><PrintTable headers={["Mezcla","Músico","Tipo","Requerimientos"]} rows={content.monitor_mixes.map(row=>[row.mix,row.musician,row.type,row.requirements])}/></PrintSection><PrintSection title="Sonido, iluminación y energía"><p><strong>PA:</strong> {content.sound.pa}</p><p><strong>Consola:</strong> {content.sound.console}</p><p><strong>Micrófonos:</strong> {content.sound.microphones}</p><p><strong>DI / Backline:</strong> {content.sound.di_boxes} · {content.sound.backline}</p><p><strong>Iluminación:</strong> {content.lighting.requirements}</p><p><strong>Energía:</strong> {content.power.voltage} · {content.power.circuits} · {content.power.grounding}</p></PrintSection><PrintSection title="Logística"><p><strong>Llegada:</strong> {content.logistics.arrival_time} · <strong>Prueba:</strong> {content.logistics.soundcheck_time}</p><p><strong>Carga:</strong> {content.logistics.load_in}</p><p><strong>Acceso:</strong> {content.logistics.access}</p><p><strong>Transporte:</strong> {content.logistics.transport}</p><p><strong>Hospitality:</strong> {content.logistics.hospitality}</p></PrintSection><PrintSection title="Contactos"><PrintTable headers={["Nombre","Rol","Teléfono","Correo"]} rows={content.contacts.map(row=>[row.name,row.role,row.phone,row.email])}/></PrintSection>{content.final_notes&&<PrintSection title="Notas finales"><p>{content.final_notes}</p></PrintSection>}</div>}
function PrintSection({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="mb-2 border-b pb-1 text-lg font-black">{title}</h2>{children}</section>}
function PrintTable({headers,rows}:{headers:string[];rows:string[][]}){return <table className="w-full border-collapse text-left text-xs"><thead><tr>{headers.map(header=><th key={header} className="border p-2">{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex} className="border p-2">{cell}</td>)}</tr>)}</tbody></table>}
function StageEditor({ rows, onChange }: { rows: StagePosition[]; onChange: (rows: StagePosition[]) => void }) { const add=()=>onChange([...rows,{id:crypto.randomUUID(),performer:"",position:"",instruments:"",power:"",notes:""}]);return <Section title="Stage plot" action={<Button type="button" onClick={add} className="rounded-xl"><Plus className="mr-2 size-4" />Posición</Button>}><div className="space-y-3">{rows.map((row,index)=><Row key={row.id} onRemove={()=>onChange(rows.filter(item=>item.id!==row.id))}><div className="grid flex-1 gap-3 sm:grid-cols-2 lg:grid-cols-5"><Field label={`Músico ${index+1}`} value={row.performer} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,performer:value}:item))}/><Field label="Posición" value={row.position} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,position:value}:item))}/><Field label="Instrumentos" value={row.instruments} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,instruments:value}:item))}/><Field label="Energía" value={row.power} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,power:value}:item))}/><Field label="Notas" value={row.notes} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,notes:value}:item))}/></div></Row>)}</div></Section> }
function InputEditor({ rows, onChange }: { rows: InputChannel[]; onChange: (rows: InputChannel[]) => void }) { const add=()=>onChange([...rows,{id:crypto.randomUUID(),channel:"",source:"",microphone:"",stand:"",phantom:false,notes:""}]);return <Section title="Input list y patch" action={<Button type="button" onClick={add} className="rounded-xl"><Plus className="mr-2 size-4" />Canal</Button>}><div className="space-y-3">{rows.map(row=><Row key={row.id} onRemove={()=>onChange(rows.filter(item=>item.id!==row.id))}><div className="grid flex-1 gap-3 sm:grid-cols-2 lg:grid-cols-6"><Field label="Canal" value={row.channel} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,channel:value}:item))}/><Field label="Fuente" value={row.source} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,source:value}:item))}/><Field label="Mic / DI" value={row.microphone} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,microphone:value}:item))}/><Field label="Soporte" value={row.stand} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,stand:value}:item))}/><Field label="Notas" value={row.notes} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,notes:value}:item))}/><div><Label>Phantom</Label><div className="mt-3"><Switch checked={row.phantom} onCheckedChange={phantom=>onChange(rows.map(item=>item.id===row.id?{...item,phantom}:item))}/></div></div></div></Row>)}</div></Section> }
function MonitorEditor({ rows, onChange }: { rows: MonitorMix[]; onChange: (rows: MonitorMix[]) => void }) { const add=()=>onChange([...rows,{id:crypto.randomUUID(),mix:`Mix ${rows.length+1}`,musician:"",type:"Monitor de piso",requirements:""}]);return <Section title="Mezclas de monitoreo" action={<Button type="button" onClick={add} className="rounded-xl"><Plus className="mr-2 size-4" />Mezcla</Button>}><div className="space-y-3">{rows.map(row=><Row key={row.id} onRemove={()=>onChange(rows.filter(item=>item.id!==row.id))}><div className="grid flex-1 gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Mezcla" value={row.mix} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,mix:value}:item))}/><Field label="Músico" value={row.musician} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,musician:value}:item))}/><Field label="Tipo" value={row.type} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,type:value}:item))}/><Field label="Necesidades" value={row.requirements} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,requirements:value}:item))}/></div></Row>)}</div></Section> }
function ContactEditor({ rows, onChange }: { rows: ProductionContact[]; onChange: (rows: ProductionContact[]) => void }) { const add=()=>onChange([...rows,{id:crypto.randomUUID(),name:"",role:"",phone:"",email:""}]);return <Section title="Contactos de producción" action={<Button type="button" onClick={add} className="rounded-xl"><Plus className="mr-2 size-4" />Contacto</Button>}><div className="space-y-3">{rows.map(row=><Row key={row.id} onRemove={()=>onChange(rows.filter(item=>item.id!==row.id))}><div className="grid flex-1 gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Nombre" value={row.name} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,name:value}:item))}/><Field label="Rol" value={row.role} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,role:value}:item))}/><Field label="Teléfono" value={row.phone} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,phone:value}:item))}/><Field label="Correo" type="email" value={row.email} onChange={value=>onChange(rows.map(item=>item.id===row.id?{...item,email:value}:item))}/></div></Row>)}</div></Section> }
function Row({children,onRemove}:{children:React.ReactNode;onRemove:()=>void}){return <div className="flex items-end gap-2 rounded-2xl border p-3">{children}<Button type="button" variant="ghost" size="icon" onClick={onRemove} className="shrink-0 rounded-xl text-destructive"><Trash2 className="size-4"/></Button></div>}
function Section({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border p-4 sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><h3 className="font-black">{title}</h3>{action}</div>{children}</section>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <div><Label>{label}</Label><Input type={type} value={value} onChange={event=>onChange(event.target.value)} className="mt-2 rounded-xl"/></div>}
function Area({label,value,onChange,className=""}:{label:string;value:string;onChange:(value:string)=>void;className?:string}){return <div className={className}><Label>{label}</Label><Textarea value={value} onChange={event=>onChange(event.target.value)} className="mt-2 min-h-24 rounded-xl"/></div>}
function formatDate(value:string){return new Intl.DateTimeFormat("es-CO",{dateStyle:"long"}).format(new Date(`${value}T12:00:00`))}
